---
##########################################################################################
#                                                                                        #
#                       Pre-commit configuration file                                    #
#                                                                                        #
#                                                                                        #
# See https://pre-commit.com for more information                                        #
# See https://pre-commit.com/hooks.html for more hooks                                   #
#                                                                                        #
# To install the git pre-commit hook run:                                                #
#   prek install                                                                         #
#   prek autoupdate                                                                      #
# To update the pre-commit hooks run:                                                    #
#   prek install-hooks                                                                   #
#   prek install --hook-type commit-msg                                                  #
# To run all hooks against current changes in your repository without committing         #
#   prek run --all-files                                                                 #
# If you wish to execute an individual hook use pre-commit run <hook_id>. Example:       #
#   prek run ruff                                                                        #
#                                                                                        #
# When making changes to the pre-commit configurations, make sure to stage it with       #
#   git add .pre-commit-config.yaml                                                      #
#                                                                                        #
##########################################################################################
fail_fast: false
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        name: check-added-large-files
        description: Prevent files larger than 2 MB from being committed.
        args: ["--maxkb=2048"]
      - id: detect-private-key
      - id: check-case-conflict
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [--profile, black]
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
        priority: 0
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest --cov=src --cov-report=term-missing
        language: system
        pass_filenames: false
