import os
import shutil
import subprocess
import tempfile

from git import GitCommandError, Repo
from github import Github

from .logger import logger


def invoke_ai_model(prompt: str) -> str:
    """
    Invoke the AI model to generate the pull request description
    """
    # Placeholder for AI model invocation logic
    # In a real implementation, this would call the AI model API with the prompt
    # and return the generated description.
    return "This is a placeholder description generated by the AI model."


def create_github_pull_request(
    repository_name: str,
    source_branch: str,
    destination_branch: str,
    title: str,
    description: str,
):
    """
    Create pull request based on the new remote branch pushed
    """
    # Use the GitHub token from environment variables
    github_token = os.environ.get("GITHUB_TOKEN")
    if not github_token:
        raise ValueError("GITHUB_TOKEN environment variable is not set")

    g = Github(github_token)

    try:
        # Get the repository
        repo = g.get_repo(repository_name)

        # Create the pull request
        pr = repo.create_pull(
            title=title, body=description, head=source_branch, base=destination_branch
        )

        logger.info(f"Pull Request Created: {pr.html_url}")
        return pr.number
    except Exception as e:
        logger.info(f"Error creating pull request: {e}")
        return None


def clone_github_repo(repo_url: str, local_dir: str | None = None):
    """
    Clone remote repository with manifests. If `local_dir` is None,
    default to a directory under the system temporary directory.
    """
    try:
        # Determine default local_dir when not provided. Prefer the project's
        # `tmp` directory (repo root / tmp). Fallback to system temp if not
        # available.
        if not local_dir:
            repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
            project_tmp = os.path.join(repo_root, "tmp")
            if not os.path.isdir(project_tmp):
                try:
                    os.makedirs(project_tmp, exist_ok=True)
                except Exception:
                    project_tmp = tempfile.gettempdir()

            repo_name = os.path.splitext(os.path.basename(repo_url))[0]
            local_dir = os.path.join(project_tmp, repo_name)

        # Ensure the target directory doesn't exist
        if os.path.exists(local_dir):
            logger.info(f"Directory {local_dir} already exists. Removing it.")
            shutil.rmtree(local_dir, ignore_errors=True)

        git_bin = "/usr/bin/git"

        # Clone the repository using full path
        subprocess.run(
            [git_bin, "clone", repo_url, local_dir],
            check=True,
            capture_output=True,
            text=True,
            shell=False,
        )

        logger.info(f"Repository successfully cloned into {local_dir}")
    except subprocess.CalledProcessError as e:
        logger.error(f"Error cloning the repository: {e.stderr}")
        raise
    except Exception as e:
        logger.error(f"An unexpected error occurred: {str(e)}")
        raise


def create_and_switch_to_branch(repo_path, new_branch_name) -> bool:
    """
    Create a new branch and switch to it locally to prepare for the pull request
    """
    try:
        repo = Repo(repo_path)

        new_branch = repo.create_head(new_branch_name)
        new_branch.checkout()

        logger.info(f"Branch '{new_branch_name}' created.")
        return True
    except GitCommandError as e:
        logger.info(f"Error creating branch {new_branch_name}: {e}")
        return False
    except Exception as e:
        logger.info(f"Unknown error: {e}")
        return False


def commit_and_push_changes(recommendations, local_dir, branch_name, repo_url) -> bool:
    """
    Commit and push all the changes to the new branch of the repository
    """
    # Initialize Git repository
    repo = Repo(local_dir)

    # Set up the remote URL with your GitHub token
    remote_url = repo_url
    origin = repo.remote("origin")
    origin.set_url(remote_url)

    # Set user name and email for Git commit
    repo.config_writer().set_value("user", "name", "Resource Updater").release()
    repo.config_writer().set_value(
        "user", "email", "resource_updater@example.com"
    ).release()

    # helper functions available in prompt_creator are intentionally not used here
    # but may be useful for callers that need the file lists/contents.

    for deployment in recommendations["metadata"]["updated_deployments"]:
        values_file_path_relative = deployment["updated_file"].split(
            "/app/manifests/", 1
        )[1]
        # Directly copy the file content without YAML parsing
        shutil.copy2(
            deployment["updated_file"], f"{local_dir}/{values_file_path_relative}"
        )

        # Commit changes
        repo.git.add(values_file_path_relative)
        repo.git.commit("-m", "Updating values with recommendations")

    # Push the new branch (optional, may require additional authentication setup)
    repo.git.push("origin", branch_name)

    logger.info(f"values.yaml updated on branch '{branch_name}'.")
    return True
